CREATE TABLE IF NOT EXISTS film (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(40),
description VARCHAR(40),
realease_date DATE,
duration INTEGER,
rating_id INTEGER
);

CREATE TABLE IF NOT EXISTS genre (
id INTEGER PRIMARY KEY,
name varchar(40) NOT null);

CREATE TABLE IF NOT EXISTS rating (
id INTEGER PRIMARY KEY,
name varchar(40) NOT null);

CREATE TABLE IF NOT EXISTS film_genre (
film_id INTEGER ,
genre_id INTEGER,
CONSTRAINT film_genre_pk PRIMARY KEY (film_id, genre_id));

CREATE TABLE IF NOT EXISTS likes (
film_id INTEGER,
user_id INTEGER,
CONSTRAINT likes_pk PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS users (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
email VARCHAR(40) unique,
login VARCHAR(40) unique ,
name VARCHAR(40),
birthday DATE
);

CREATE TABLE IF NOT EXISTS friendship (
user_id INTEGER,
friend_id INTEGER,
status boolean,
CONSTRAINT friendship_pk PRIMARY KEY (user_id, friend_id));
